### ISSUE TITLE
Add a team page landing, and then a seperate /team/username per team member

### ISSUE THREAD

**Issue by ByteOfMelon** [Melonz/melonz.github.io#3]
Gonna assign this to @aerofusionyt

(well i would but he hasn't accepted the invite yet)

Here's the rundown:

**/team/** - Team landing page. Shows all the members, and clicking on their names goes to their specific page. Only one link should be displayed on the landing page.

**/team/username** - Team member detail (e.g /team/therandommelon would be mine). Includes a detailed description, all of their social links (up to 5), etc.

**Comment by ghost** [comment]
i'll get around to it ya bastard

**Comment by t5r7** [comment]
Use [Jekyll collections](https://jekyllrb.com/docs/collections/) here, would be pretty easy to manage

**Comment by t5r7** [comment]
Added in https://github.com/Melonz/melonz.github.io/commit/742fd5ff93c86fb9d6069c39de79c5f4e2935f86

Won't close this issue until the placeholder members are updated though.

**Comment by ByteOfMelon** [comment]
After my 40 millionth commit, the team page is complete.
