### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by TheRandomMelon** [Melonz/melonz.github.io#5]
Add search functionality via https://github.com/christian-fei/Simple-Jekyll-Search

**Comment by TheRandomMelon** [comment]
Use this for the search box: https://bulma.io/documentation/form/input/

**Comment by TheRandomMelon** [comment]
This is to be done ONLY after the Bulma redesign.

**Comment by mrdnomaid** [comment]
Feel free to copy my code from here if you're feeling lazy, future melon

https://github.com/mrdnomaid/mrdnomaid.github.io/tree/master/search
https://github.com/mrdnomaid/mrdnomaid.github.io/blob/master/_includes/search.html

**Comment by mrdnomaid** [comment]
Going to add this after @TheRandomMelon has finished with the Bulma redesign, which, hopefully, will be quite soon.

**Comment by TheRandomMelon** [comment]
@mrdnomaid Don't close issues until they're 100% done

**Comment by mrdnomaid** [comment]
Well, it's added now

https://github.com/Melonz/melonz.github.io/commit/541d76444bb0713f8f38b43031276f376ca9d795
